// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/state/Provider"; // Use the new Providers component

export const metadata: Metadata = {
  title: "WanderStay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers> {/* Wrap with Providers */}
      </body>
    </html>
  );
}
